#include <string>
#include <sstream>
using namespace std;

// before "@": class name, written by developer
// after  "@": IR vptr symbol, generated by ivt_change
// return IR vptr symbol if exists, n is changed to class name
string trim(string & n) {
    string res = "";
    size_t np = n.find("@");
    if (np != string::npos) {
      res = n.substr(np + 1);
      n = n.substr(0, np);
    }
    return res;
}
// convert class name to IR class symbol
string name2clsn(string n) {
  return string("class.") + n;
}
// convert class name to IR vptr symbol
string name2vptr(string n) {
    bool with_ns = false;
    ostringstream res;
    res << "@_ZTV";
    size_t p = 0, l = n.length();
    while (p < l) {
        size_t np = n.find("::", p);
        if (np == string::npos) {
            np = l;
        } else {
            if (!with_ns)
                res << "N";
            with_ns = true;
        }
        string s = n.substr(p, np - p);
        res << s.length() << s;
        p = np + 2;
    }
    if (with_ns)
      res << "E";
    res << ",";
    return res.str();
}
// convert class name to IR constructor symbol
string name2ctor(string n) {
    ostringstream res;
    res << "_ZN";
    size_t p = 0, l = n.length();
    while (p < l) {
        size_t np = n.find("::", p);
        if (np == string::npos)
            np = l;
        string s = n.substr(p, np - p);
        res << s.length() << s;
        p = np + 2;
    }
    return res.str();
}

